### ISSUE TITLE
Update to latest lottie

### ISSUE THREAD

**Issue by galipmedia** [transitive-bullshit/puppeteer-lottie#22]
I am having some weird kerning issues with my text, but its working fine locally on web version. I am wondering if something has been fixed as lottie has had many upgrades in the past 5 months.

**Comment by galipmedia** [comment]
That was not my issue after all.

**Comment by transitive-bullshit** [comment]
Hey, would you mind posting what your issue was so other users can benefit from it if they're having a similar issue?

Thanks!

**Comment by galipmedia** [comment]
To be honest it was one of those moments where I am not sure exactly what fixed it as I was frantically changing various things. It was either the fPath needing to not be blank (which is weird because I am using a google font) or it was needing to export it in legacy format or it may have been a misuse of the inject style (which never seems to do anything for me). I will report back if I find out exactly what has fixed the issue.

**Comment by galipmedia** [comment]
After some retracing of steps (i think) it is if you use the bodymovin advanced setting for legacy json it causes this issue.

**Comment by transitive-bullshit** [comment]
Sounds good -- really appreciate you taking the time to track this down. 🙏

**Comment by wonyeouuu** [comment]
@galipmedia Dude you're my hero! I was struggling with the same issue 🙏
