### ISSUE TITLE
Array of tasks

### ISSUE THREAD

**Issue by galipmedia** [transitive-bullshit/puppeteer-lottie#24]
It would be cool if it could accept an array of objects to render so that you do not have to open and close the browser in a loop. I am experiencing high CPU and I am wondering if opening and closing the browser is causing this.

**Comment by galipmedia** [comment]
I have clustered it with a queue and its working much smoother now.

**Comment by transitive-bullshit** [comment]
https://github.com/sindresorhus/p-map is what I would use for this.
