### ISSUE TITLE
How to render a specific frame?

### ISSUE THREAD

**Issue by amansingh7010** [transitive-bullshit/puppeteer-lottie#40]
Hi, thanks for the amazing tool that you developed. 
I am trying to render a specific frame within a 750 frame animation. The tool only allows me to either render the first frame or all the frames. Am I missing something? Or this feature is not currently supported?

**Comment by affankhan43** [comment]
I just build the solution for this problem using lottie-web 
Lottie-web load animation has an option named as initialSegment
In this option, you can mention specific frame number,

**Comment by affankhan43** [comment]
checkout this
https://github.com/transitive-bullshit/puppeteer-lottie/pull/44/commits/c0bcd90bcd228e710c07d8a83039747d80318a2c

**Comment by amansingh7010** [comment]
Thanks for the solution. 👍 
However, I ended up using puppeteer only.

**Comment by affankhan43** [comment]
@amansingh7010  what you using now, because I'm facing low-speed rendering in puppeteer

**Comment by amansingh7010** [comment]
@affankhan43 so my goal was to save the specific frames as images. I rendered the animation in puppeteer, used `anim.goToAndStop(value, isFrame)` from `lottie` library, and took screenshot using `page.screenshot()` from `puppeteer` library.
