### ISSUE TITLE
Can't make it work

### ISSUE THREAD

**Issue by Tarifut** [transitive-bullshit/puppeteer-lottie#49]
Hi, i can't make it work:
I tried the library and the CLI version (last debian, fresh nodejs v15 and npm install. Lottie json from official lottie hub)
For the library I used sample code:

await renderLottie({

SyntaxError: await is only valid in async function

And for the library AND the CLI,i always have chromium errors (libXss -> i installed dependencies-> libcairo error etc.....)

Example: " Loading browser(node:475) UnhandledPromiseRejectionWarning: Error: Failed to launch the browser process!
/node_modules/puppeteer-lottie/node_modules/puppeteer/.local-chromium/linux-722234/chrome-linux/chrome: error while loading shared libraries: libXss.so.1: cannot open shared object file: No such file or directory"

How do you make it work?

**Comment by Tarifut** [comment]
Nevermind, made it work ;)

**Comment by balanikaran** [comment]
That's great, glad.
Please make sure you close the issue in such cases. :)

**Comment by qiuliliang** [comment]
so,i am the same problem, how did u fix it?

**Comment by mairin** [comment]
how did you make it work? have the same issue on linux :(
