### ISSUE TITLE
Protocol error (Page.captureScreenshot): Target closed. 

### ISSUE THREAD

**Issue by avasilic** [transitive-bullshit/puppeteer-lottie#65]
I'm getting the error `Protocol error (Page.captureScreenshot): Target closed. ` when running puppeteer-lottie. It seems like its related to https://github.com/puppeteer/puppeteer/issues/1385. https://github.com/puppeteer/puppeteer/issues/1385#issuecomment-346164928 suggests a fix to this person's specific code but it looks like a similar code line somewhere in the index file may be the issue.

**Comment by avasilic** [comment]
Fixed it myself.

**Comment by dave3vans** [comment]
how did you fix this?

**Comment by avasilic** [comment]
> how did you fix this?

If I remember correctly, I just ended up switching to MP4 format.
